--1.What is the total revenue generated by the company each month?
SELECT
    FORMAT(start_date, 'yyyy-MM') AS month,
    round(SUM(total_amount),2) AS total_revenue
FROM
    rentals_data
GROUP BY
    FORMAT(start_date, 'yyyy-MM')
ORDER BY
    FORMAT(start_date, 'yyyy-MM');

--2.How many unique customers rented vehicles in each city?
SELECT
    city, count(distinct c.customer_id) as unique_cust
FROM
    customers_data c
JOIN
    rentals_data r ON c.customer_id = r.customer_id
GROUP BY
    city;

--3.Which vehicle category has the highest rental demand?
SELECT TOP (1)
    category,
    COUNT(*) AS rental_count
FROM
    vehicles_data v
JOIN
    rentals_data r ON v.vehicle_id = r.vehicle_id
GROUP BY
    category
ORDER BY
rental_count DESC

--4.What is the average rental duration for each vehicle category?
SELECT
    category,
    AVG(rental_duration_days) AS avg_rental_duration
FROM
    vehicles_data v
JOIN
    rentals_data r ON v.vehicle_id = r.vehicle_id
GROUP BY
    category
order by avg_rental_duration desc

--5.How many rentals were made by customers in each age group?
SELECT
    age_group,
    COUNT(*) AS rental_count
FROM
    (SELECT
        CASE
            WHEN age < 25 THEN 'Under 25'
            WHEN age >= 25 AND age < 35 THEN '25-34'
            WHEN age >= 35 AND age < 45 THEN '35-44'
            WHEN age >= 45 AND age < 55 THEN '45-54'
            ELSE '55+'
        END AS age_group
    FROM
        customers_data c
    JOIN
        rentals_data r ON c.customer_id = r.customer_id) AS subquery
GROUP BY
    age_group
order by rental_count DESC

--6.What is the average rental rate per day for each vehicle make?
SELECT
    make,
    floor(AVG(rental_rate_per_day)) AS avg_rental_rate
FROM
    vehicles_data
GROUP BY
    make
order by avg_rental_rate DESC

--7.How many rentals exceeded the expected rental duration?
SELECT
    COUNT(*) AS rentals_exceeding_duration
FROM
    rentals_data
WHERE
    rental_duration_days > DATEDIFF(day,end_date, start_date);

--8.What is the average total amount spent per customer?
SELECT
    customer_id,
    ROUND(AVG(total_amount),2) AS avg_total_amount
FROM
    rentals_data
GROUP BY
    customer_id
ORDER BY avg_total_amount desc

--9.Are there any seasonal trends in rental demand?
SELECT
    FORMAT(start_date, 'MM') AS month,
    COUNT(*) AS rental_count
FROM
    rentals_data
GROUP BY
    FORMAT(start_date, 'MM')
ORDER BY
    FORMAT(start_date, 'MM')

--10.How does customer satisfaction vary based on rental duration?
SELECT
    CASE
        WHEN rental_duration_days < 3 THEN 'Low'
        WHEN rental_duration_days >= 3 AND rental_duration_days < 7 THEN 'Medium'
        ELSE 'High'
    END AS satisfaction_level,
    COUNT(*) AS rental_count
FROM
    rentals_data
GROUP BY
    CASE
        WHEN rental_duration_days < 3 THEN 'Low'
        WHEN rental_duration_days >= 3 AND rental_duration_days < 7 THEN 'Medium'
        ELSE 'High'
    END